### ISSUE TITLE
Support for FVXM-A?

### ISSUE THREAD

**Issue by dhermanns** [arska/python-daikinapi#5]
Hi!

Thanks for your great work! Should the 2020 Model FVXM-A of the Daikin
Air Conditioner work with your library?

**Comment by arska** [comment]
Hi @dhermanns,

Thanks for your patience!

Can you test the compatibility with your model so we can list it as working?

Cheers,
Aarno

**Comment by dhermanns** [comment]
Hi @arska !

Great to hear that my device should be supported now. For sure I will have a look and let you know!

**Comment by dhermanns** [comment]
Hi @arska!

Ich checked out the latest master branch and just tried the example.py like:

`python example.py 192.168.0.134`

But that just returns:

`Traceback (most recent call last):
  File "/Users/dirk/workspace/python-daikinapi/example.py", line 34, in <module>
    print(API)
  File "/Users/dirk/workspace/python-daikinapi/daikinapi.py", line 364, in __str__
    return f"Daikin(host={self._host},name={self.name},mac={self.mac})"
  File "/Users/dirk/workspace/python-daikinapi/daikinapi.py", line 271, in name
    return self._get_basic()["name"]
  File "/Users/dirk/workspace/python-daikinapi/daikinapi.py", line 80, in _get_basic
    return self._get("/common/basic_info")
  File "/Users/dirk/workspace/python-daikinapi/daikinapi.py", line 51, in _get
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.0.134/common/basic_info`

**Comment by arska** [comment]
Hello @dhermanns, seems not to be compatible, maybe it has the newer (cloud) wifi module like the user in https://github.com/arska/python-daikinapi/issues/6
